//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musify.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Musify.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musify.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musify.
        /// </summary>
        public static string ApplicationTitle1 {
            get {
                return ResourceManager.GetString("ApplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name:.
        /// </summary>
        public static string DisplayNameCaption {
            get {
                return ResourceManager.GetString("DisplayNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is turned off. To see the current Bluetooth settings tap &apos;ok&apos;..
        /// </summary>
        public static string Err_BluetoothOff {
            get {
                return ResourceManager.GetString("Err_BluetoothOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Off.
        /// </summary>
        public static string Err_BluetoothOffCaption {
            get {
                return ResourceManager.GetString("Err_BluetoothOffCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run this app, you must have ID_CAP_PROXIMITY enabled in WMAppManifest.xaml.
        /// </summary>
        public static string Err_MissingCaps {
            get {
                return ResourceManager.GetString("Err_MissingCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a your name to connect..
        /// </summary>
        public static string Err_NoChatName {
            get {
                return ResourceManager.GetString("Err_NoChatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name is empty.
        /// </summary>
        public static string Err_NoChatNameCaption {
            get {
                return ResourceManager.GetString("Err_NoChatNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect.
        /// </summary>
        public static string Err_NoConnectTitle {
            get {
                return ResourceManager.GetString("Err_NoConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to a Peer..
        /// </summary>
        public static string Err_NoPeerConnected {
            get {
                return ResourceManager.GetString("Err_NoPeerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send.
        /// </summary>
        public static string Err_NoSendTitle {
            get {
                return ResourceManager.GetString("Err_NoSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently not advertising yourself..
        /// </summary>
        public static string Err_NotAdvertising {
            get {
                return ResourceManager.GetString("Err_NotAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;--  {0}
        ///.
        /// </summary>
        public static string Format_IncomingMessageNoName {
            get {
                return ResourceManager.GetString("Format_IncomingMessageNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}
        ///.
        /// </summary>
        public static string Format_IncomingMessageWithName {
            get {
                return ResourceManager.GetString("Format_IncomingMessageWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [me] {0} 
        ///.
        /// </summary>
        public static string Format_OutgoingMessage {
            get {
                return ResourceManager.GetString("Format_OutgoingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows you how to perform app to app communication using Bluetooth. It demonstrates how to find peer apps, establish a connection and send and receive data..
        /// </summary>
        public static string InstructionsText {
            get {
                return ResourceManager.GetString("InstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join chat.
        /// </summary>
        public static string JoinPageTitle {
            get {
                return ResourceManager.GetString("JoinPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}!.
        /// </summary>
        public static string Msg_ConnectedTo {
            get {
                return ResourceManager.GetString("Msg_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page name.
        /// </summary>
        public static string PageTitle1 {
            get {
                return ResourceManager.GetString("PageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButtonCaption {
            get {
                return ResourceManager.GetString("SendButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name to use:.
        /// </summary>
        public static string ServiceFieldPrompt {
            get {
                return ResourceManager.GetString("ServiceFieldPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample requires the Bluetooth radio to be turned on. Bluetooth is not available on the emulator. To experience this sample, run it on a Windows Phone 8 device..
        /// </summary>
        public static string Warn_EmulatorMode {
            get {
                return ResourceManager.GetString("Warn_EmulatorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted operation in emulator..
        /// </summary>
        public static string Warn_EmulatorModeTitle {
            get {
                return ResourceManager.GetString("Warn_EmulatorModeTitle", resourceCulture);
            }
        }
    }
}
